// hola هلو 
let challenge = "30 Days Of JavaScript";
console.log(challenge);
console.log(challenge.length);
console.log(challenge.toUpperCase());
console.log(challenge.toLowerCase());
console.log(challenge.substr(0,2));
console.log(challenge.substr(3,18));
console.log(challenge.includes('Script '));
console.log(challenge.split(""));
console.log(challenge.split(" "));
let company = 'Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon';
console.log(company.split(","));
console.log(challenge.replace("JavaScript","Python "));
console.log(challenge.charAt(15));
console.log(challenge.charCodeAt(11));
console.log(challenge.indexOf(30));
console.log(challenge.lastIndexOf("JavaScript"));
let b = 'You cannot end a sentence with because because because is a conjunction';
console.log(b.indexOf("because"));
console.log(b.lastIndexOf("because"));
console.log(b.search("because"));
console.log(challenge.trim(" "));
console.log(challenge.startsWith("30"));
console.log(challenge.endsWith("JavaScript "));
console.log(challenge.match("a"));
let sinString = "";
console.log(sinString.concat( '30 Days of',"javascript"));
console.log(challenge.repeat(2));